/**
 * Master Classical Pilates and Kinesitherapy Seed Catalog (49 Exercises)
 * Pilates Espaço Mulher — Dra. Rogéria Collares (CREFITO 23093-F)
 * 
 * Repertoire organized across all 6 apparatuses:
 * 1. Mat / Solo (13)
 * 2. Reformer (8)
 * 3. Cadillac (8)
 * 4. Wunda Chair (7)
 * 5. Ladder Barrel (6)
 * 6. Cinesioterapia & Acessórios (7)
 */

import { SQLiteDatabase } from 'expo-sqlite';
import { Exercise } from '../types/exercise';

export const CLASSICAL_EXERCISES_CATALOG: Exercise[] = [
  // ==========================================
  // 1. Mat / Solo (13 Exercises)
  // ==========================================
  {
    id: 'mat-the-hundred',
    name: 'The Hundred (O Cento)',
    apparatus: 'Mat',
    description: 'Decúbito dorsal, pernas a 45º (ou tabletop), flexão torácica elevando escápulas do solo. Bombeamento rítmico e vigoroso dos braços estendidos, 5 batimentos na inspiração e 5 na expiração até 100 respirações. Powerhouse ativado, foco em estabilização lombopélvica.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '100 bombeamentos',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Ativação do Powerhouse, estabilização lombopélvica e aquecimento circulatório',
    contraindications: 'Hérnia discal cervical aguda, osteoporose severa (evitar flexão extrema)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-the-roll-up',
    name: 'The Roll Up (Rolamento para Cima)',
    apparatus: 'Mat',
    description: 'Decúbito dorsal, braços apontando para o teto. Iniciar pela flexão cervical, articulando vértebra por vértebra para descolar do solo em formato de C até alcançar os pés. Retornar desenrolando lentamente sem despencar.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '5-8',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Articulação segmentar da coluna e fortalecimento abdominal profundo',
    contraindications: 'Osteoporose lombar severa, hérnia discal com dor à flexão',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-single-leg-circles',
    name: 'Single Leg Circles (Círculos com Uma Perna)',
    apparatus: 'Mat',
    description: 'Decúbito dorsal, uma perna estendida para cima a 90º e a perna de apoio firme no solo em dorsiflexão. Realizar círculos controlados a partir da cabeça do fêmur sem oscilação da pelve (5 em cada sentido por perna).',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '5 cada sentido',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Mobilidade coxofemoral e estabilidade pélvica unilateral',
    contraindications: 'Impacto femoroacetabular sintomático',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-rolling-like-a-ball',
    name: 'Rolling Like a Ball (Rolando como uma Bola)',
    apparatus: 'Mat',
    description: 'Sentado em equilíbrio sobre os ísquios, joelhos flexionados junto ao peito, mãos nos tornozelos, coluna em flexão contínua (C-curve). Rolar para trás até a base das escápulas e retornar ao ponto de equilíbrio sem apoiar os pés no solo.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '6-8',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Massagem nos eretores da espinha e controle do equilíbrio sobre os ísquios',
    contraindications: 'Instabilidade cervical, dor aguda na coluna vertebral',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-single-leg-stretch',
    name: 'Single Leg Stretch (Alongamento com Uma Perna)',
    apparatus: 'Mat',
    description: 'Decúbito dorsal com tronco em flexão torácica, uma perna flexionada ao peito (mão externa no tornozelo, mão interna no joelho) e a perna contralateral estendida a 45º. Alternar de forma rítmica mantendo pelve estável e abdômen afundado.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '10 cada lado',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Coordenação motora, resistência do core e estabilização lumbopélvica',
    contraindications: 'Dor cervical não compensada (apoiar a cabeça no solo)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-double-leg-stretch',
    name: 'Double Leg Stretch (Alongamento com Ambas as Pernas)',
    apparatus: 'Mat',
    description: 'Decúbito dorsal em flexão torácica, abraçando os joelhos. Inspirar estendendo simultaneamente braços para trás e pernas para frente a 45º. Expirar circulando os braços e recolhendo os joelhos, mantendo a lombar protegida pelo core.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '8-10',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Fortalecimento do transverso do abdômen e estabilidade axial',
    contraindications: 'Lombalgia mecânica aguda (reduzir ângulo das pernas para 90º)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-spine-stretch-forward',
    name: 'Spine Stretch Forward (Alongamento da Coluna para Frente)',
    apparatus: 'Mat',
    description: 'Sentado ereto sobre os ísquios, pernas afastadas na largura dos ombros, pés em dorsiflexão. Expirar enrolando o tronco para frente a partir da cervical, alcançando as mãos à frente enquanto o abdômen contrai para trás em oposição.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '5-6',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Mobilização torácica em flexão e alongamento da cadeia posterior',
    contraindications: 'Hérnia discal lombar sintomática em flexão',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-the-saw',
    name: 'The Saw (A Serra)',
    apparatus: 'Mat',
    description: 'Sentado com pernas afastadas e braços abertos em cruz. Rodar o tronco e flexionar à frente serrando o dedo mínimo do pé oposto com a mão dianteira, enquanto o braço de trás gira internamente. Manter ambos os ísquios firmemente apoiados.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '4 cada lado',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Rotação espinhal com flexão e alongamento dos isquiotibiais',
    contraindications: 'Dor sacroilíaca aguda em rotação',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-swan',
    name: 'Swan (O Cisne)',
    apparatus: 'Mat',
    description: 'Decúbito ventral, mãos apoiadas sob os ombros. Inspirar elevando o esterno do solo em extensão torácica pura, mantendo transverso abdominal ativo para proteger a coluna lombar e pernas aduzidas.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '5-6',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Extensão torácica pura, correção de postura hipercifótica e fortalecimento dorsal',
    contraindications: 'Espondilolistese e estenose de canal lombar sintomática em extensão',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-swimming',
    name: 'Swimming (Natação)',
    apparatus: 'Mat',
    description: 'Decúbito ventral, braços e pernas estendidos flutuando no ar. Bater alternadamente braço direito/perna esquerda e braço esquerdo/perna direita com respiração coordenada, fortalecendo a cadeia posterior sem sobrecarga lombar.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '20-30 batimentos',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Fortalecimento da cadeia posterior cruzada e eretores da coluna',
    contraindications: 'Pinçamento subacromial agudo de ombro',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-the-teaser',
    name: 'The Teaser (O Provocador Solo)',
    apparatus: 'Mat',
    description: 'Decúbito dorsal. Elevar simultaneamente tronco e pernas em formato de V perfeito, braços paralelos aos membros inferiores, sustentando o centro de gravidade sobre os ísquios antes de descer articulando cada vértebra.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '3-5',
    default_sets: 1,
    level: 'avançado',
    postural_focus: 'Controle neuromuscular avançado, equilíbrio sobre os ísquios e força total do core',
    contraindications: 'Fraqueza abdominal pronunciada, dor lombar aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-prancha-frontal',
    name: 'Prancha Frontal (Prancha Isométrica)',
    apparatus: 'Mat',
    description: 'Apoio de antebraços e pontas dos pés no solo, alinhando cabeça, tronco e quadril em prancha estável. Co-contração de transverso do abdômen, glúteos e serrátil anterior sem desabar a pelve.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '30-45 segundos',
    default_sets: 3,
    level: 'iniciante',
    postural_focus: 'Estabilização de core global e cintura escapular',
    contraindications: 'Hipertensão arterial não controlada (manter respiração constante)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mat-perdigueiro',
    name: 'Perdigueiro (Bird Dog / Quatro Apoios)',
    apparatus: 'Mat',
    description: 'Posição de quatro apoios. Estender simultaneamente braço direito à frente e perna esquerda atrás alinhados com o tronco. Manter pelve e ombros rigorosamente horizontais, fortalecendo multífidos e core.',
    default_springs: 'N/A (Peso Corporal)',
    default_reps: '10 cada lado',
    default_sets: 2,
    level: 'iniciante',
    postural_focus: 'Estabilização rotacional e ativação profunda de multífidos',
    contraindications: 'Síndrome do túnel do carpo (apoiar sobre punhos fechados ou antebraços)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 2. Reformer (8 Exercises)
  // ==========================================
  {
    id: 'reformer-footwork',
    name: 'Footwork (Trabalho de Pés)',
    apparatus: 'Reformer',
    description: 'Decúbito dorsal no carrinho, pés na barra em 4 posições clássicas: Dedos (Toes), Arcos (Arches), Calcanhares (Heels) e Alongamento do Tendão (Tendon Stretch). Empurrar o carrinho estendendo joelhos e flexionar com retorno excêntrico controlado.',
    default_springs: '3 a 4 Molas (3 Vermelhas ou 2 Vermelhas + 1 Azul)',
    default_reps: '10 cada posição',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Alinhamento de membros inferiores, fortalecimento de quadríceps e arcos plantares',
    contraindications: 'Lesão aguda de menisco ou ligamentos do joelho',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-the-hundred',
    name: 'The Hundred no Reformer (Cento no Reformer)',
    apparatus: 'Reformer',
    description: 'Decúbito dorsal, pernas a 45º ou tabletop, alças curtas nas mãos empurrando contra as molas com flexão torácica e bombeamento de braços. Foco em estabilidade escapuloumeral e ativação profunda do assoalho pélvico.',
    default_springs: '2 Molas (1 Vermelha + 1 Azul)',
    default_reps: '100 bombeamentos',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Estabilização de tronco contra a resistência elástica e conexão escapular',
    contraindications: 'Patologia aguda de disco cervical',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-leg-circles-frog',
    name: 'Leg Circles & Frog (Círculos de Perna e Sapo)',
    apparatus: 'Reformer',
    description: 'Decúbito dorsal com alças longas nos pés. Frog: flexionar e estender joelhos mantendo calcanhares unidos em rotação externa suave. Circles: círculos simétricos mantendo a pelve totalmente neutra.',
    default_springs: '2 Molas (1 Vermelha + 1 Azul)',
    default_reps: '8-10 cada',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Mobilização coxofemoral, adutores e estabilidade pélvica',
    contraindications: 'Bursite trocantérica aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-stomach-massage',
    name: 'Stomach Massage Series (Massagem Estomacal)',
    apparatus: 'Reformer',
    description: 'Sentado no carrinho próximo à borda frontal, pés na barra: Round Back (coluna em C), Flat Back (coluna ereta neutra), Reach Up (braços elevados) e Twist (rotação com alcance lateral). Empurrar o carrinho com as pernas, baixar e subir calcanhares.',
    default_springs: '3 a 2 Molas (Inicia com 3, reduz para 2)',
    default_reps: '8-10 cada variação',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Mobilidade torácica, dorsiflexão de tornozelo e força do core sentado',
    contraindications: 'Dor aguda de ciático com encurtamento severo de isquiotibiais',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-short-box',
    name: 'Short Box Series (Série da Caixa Curta)',
    apparatus: 'Reformer',
    description: 'Sentado na caixa transversal com pés firmes sob a fita de segurança: Round (enrolando em C), Flat (inclinação dorsal reta), Side to Side (inclinações laterais), Twist with Reach e Tree (alongamento da árvore com pegada na coxa).',
    default_springs: 'Todas as Molas Travadas (4 Molas)',
    default_reps: '5 cada movimento',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Alongamento axial, flexão lateral e controle excêntrico da coluna lombar',
    contraindications: 'Instabilidade de coluna lombar (evitar Flat back profundo)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-the-elephant',
    name: 'The Elephant (O Elefante)',
    apparatus: 'Reformer',
    description: 'Em pé no carrinho, calcanhares apoiados nas ombreiras, mãos na barra de pés, tronco flexionado em C ou neutro. Empurrar o carrinho apenas com o movimento articular dos ombros e puxar de volta pela força do abdômen, sem balançar o quadril.',
    default_springs: '2 Molas Vermelhas',
    default_reps: '8-10',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Alongamento dos isquiotibiais, estabilidade da cintura escapular e força abdominal reversa',
    contraindications: 'Encurtamento extremo de cadeia posterior (flexionar levemente os joelhos)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-long-stretch',
    name: 'Long Stretch Series (Série de Alongamento Longo)',
    apparatus: 'Reformer',
    description: 'Posição de prancha alta no carrinho com pés nas ombreiras e mãos na barra. Empurrar o carrinho para trás a partir dos ombros e puxar de volta mantendo prancha impecável. Progressão para Down Stretch e Up Stretch.',
    default_springs: '2 Molas Vermelhas',
    default_reps: '5-6',
    default_sets: 1,
    level: 'avançado',
    postural_focus: 'Força escapulotorácica avançada, anti-extensão lombar e alinhamento axial',
    contraindications: 'Lesão do manguito rotador, fraqueza severa de transverso',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'reformer-short-spine',
    name: 'Short Spine Massage (Massagem da Coluna Curta)',
    apparatus: 'Reformer',
    description: 'Decúbito dorsal com alças nos pés. Estender em 45º, elevar pernas e pelve em rolamento articulado até o apoio nas escápulas, flexionar joelhos em direção aos ombros e desenrolar a coluna no carrinho vértebra por vértebra.',
    default_springs: '2 Molas (1 Vermelha + 1 Azul)',
    default_reps: '5',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Descompressão espinhal, mobilidade e massagem articular vertebral',
    contraindications: 'Osteopenia/Osteoporose acentuada, glaucoma, patologias cervicais',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 3. Cadillac / Trapézio (8 Exercises)
  // ==========================================
  {
    id: 'cadillac-roll-down',
    name: 'Roll Down com Barra de Madeira (Rolamento para Baixo)',
    apparatus: 'Cadillac',
    description: 'Sentado de frente para a torre segurando a barra Roll-Down. Enrolar a coluna para trás até o apoio sacral e torácico, articulando vértebra a vértebra, e retornar mobilizando a coluna com alívio das tensões lombares.',
    default_springs: '2 Molas Amarelas Superiores',
    default_reps: '8-10',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Mobilização da coluna vertebral e controle abdominal assistido por molas',
    contraindications: 'Instabilidade espondilolítica não consolidada',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-the-tower',
    name: 'The Tower (A Torre)',
    apparatus: 'Cadillac',
    description: 'Decúbito dorsal, pés na barra Push-Through (conectada por baixo com corrente de proteção). Estender joelhos elevando a pelve e a coluna vértebra por vértebra até o apoio escapular, flexionar joelhos no topo e descer com controle.',
    default_springs: '1 a 2 Molas Amarelas / Vermelhas Inferiores (com Corrente)',
    default_reps: '6-8',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Alongamento de isquiotibiais e articulação segmentar da coluna em cadeia fechada',
    contraindications: 'Cervicalgia aguda, hérnia de disco sintomática em flexão e carga',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-the-monkey',
    name: 'The Monkey (O Macaco)',
    apparatus: 'Cadillac',
    description: 'Decúbito dorsal, mãos e pés segurando a barra Push-Through conectada por baixo. Flexionar profundamente os joelhos em direção ao peito e estender os membros inferiores alongando intensamente os isquiotibiais e mobilizando os pés.',
    default_springs: '1 Mola Vermelha ou 2 Amarelas Inferiores (com Corrente)',
    default_reps: '6-8',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Alongamento da cadeia posterior, descompressão lombar e mobilidade de tornozelos',
    contraindications: 'Lesão aguda de joelho em flexão profunda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-cat-stretch',
    name: 'Cat Stretch no Cadillac (Alongamento do Gato)',
    apparatus: 'Cadillac',
    description: 'Ajoelhado de frente para a barra Push-Through conectada por cima. Flexionar a coluna empurrando a barra para baixo em C, articular para extensão torácica e retornar mobilizando suavemente cada segmento da coluna.',
    default_springs: '1 Mola Amarela ou Azul Superior',
    default_reps: '6-8',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Mobilização tridimensional da coluna vertebral e conscientização respiratória',
    contraindications: 'Dor patelofemoral aguda ao ajoelhar (utilizar almofada de alívio)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-breathing',
    name: 'Breathing no Trapézio (Respiração e Elevação Pélvica)',
    apparatus: 'Cadillac',
    description: 'Decúbito dorsal, pés apoiados na fita do trapézio ou barra móvel, mãos segurando as colunas verticais. Elevar a pelve em ponte com respiração profunda sincronizada com a expansão da caixa torácica.',
    default_springs: '2 Molas de Trapézio',
    default_reps: '6-8',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Expansão costolateral da respiração e ativação de glúteos em cadeia aberta',
    contraindications: 'Câimbras recorrentes em isquiotibiais (ajustar distância da barra)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-chest-expansion',
    name: 'Chest Expansion (Expansão Torácica)',
    apparatus: 'Cadillac',
    description: 'Ajoelhado na cama do Cadillac segurando as alças de mão das molas de braço. Puxar as alças para trás até a linha do quadril, abrir a caixa torácica, girar o pescoço para a direita e esquerda, e retornar controlando a tensão excêntrica.',
    default_springs: '2 Molas Amarelas Médias de Braço',
    default_reps: '6-8',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Abertura anterior de ombros, fortalecimento de romboides e mobilidade cervical',
    contraindications: 'Instabilidade anterior de ombro em extensão extrema',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-leg-springs',
    name: 'Leg Springs Series (Série de Molas de Perna)',
    apparatus: 'Cadillac',
    description: 'Decúbito dorsal com alças nos pés conectadas às molas verticais: Círculos (Circles), Sapinho (Frog), Tesouras (Scissors) e Caminhada (Walking), fortalecendo adutores, quadríceps e estabilizadores pélvicos.',
    default_springs: '2 Molas Verdes ou Roxas Médias de Perna',
    default_reps: '10 cada movimento',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Dissociação lumbopélvica e fortalecimento excêntrico de membros inferiores',
    contraindications: 'Dor sacroilíaca mecânica aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cadillac-teaser-push-through',
    name: 'Teaser com Barra Push-Through (Teaser no Cadillac)',
    apparatus: 'Cadillac',
    description: 'Decúbito dorsal com cabeça voltada para a torre, mãos na barra Push-Through. Conectar a força dos membros superiores ao abdômen, elevando simultaneamente o tronco e as pernas em Teaser com suporte elástico.',
    default_springs: '1 Mola Amarela Superior',
    default_reps: '4-6',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Fortalecimento abdominal integrado à cintura escapular com assistência da mola',
    contraindications: 'Fraqueza cervical severa',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 4. Wunda Chair (7 Exercises)
  // ==========================================
  {
    id: 'chair-footwork',
    name: 'Footwork na Cadeira (Trabalho de Pés na Chair)',
    apparatus: 'Wunda Chair',
    description: 'Sentado ereto no topo do assento, mãos apoiadas atrás. Pressionar o pedal para baixo com dedos (Toes), arcos (Arches) e calcanhares (Heels), mantendo estabilidade pélvica e crescimento axial da coluna.',
    default_springs: '2 Molas Altas (ex.: 2 Pretas pos. 3)',
    default_reps: '10-12 cada posição',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Alinhamento postural sentado, arcos do pé e tônus de membros inferiores',
    contraindications: 'Fasciíte plantar aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'chair-going-up-front',
    name: 'Going Up Front (Subida Frontal / Step Up)',
    apparatus: 'Wunda Chair',
    description: 'Em pé em frente à cadeira, um pé no pedal e o outro firme no topo do assento. Subir estendendo a perna de apoio com controle rigoroso do quadríceps e estabilidade da pelve, sem deixar o pedal bater embaixo na descida excêntrica.',
    default_springs: '1 Mola Alta + 1 Mola Baixa (pos. 3 e 1)',
    default_reps: '8-10 cada perna',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Controle neuromuscular de membros inferiores, equilíbrio unipodal e força de glúteo',
    contraindications: 'Instabilidade severa de tornozelo ou labirintopatia ativa',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'chair-press-down',
    name: 'Press Down / Pumping (Pressionar para Baixo)',
    apparatus: 'Wunda Chair',
    description: 'Em pé atrás da cadeira, mãos no assento, um pé pressionando o pedal para baixo em flexão plantar e extensão de quadril, fortalecendo glúteo máximo e isquiotibiais com sustentação do core.',
    default_springs: '1 a 2 Molas Médias',
    default_reps: '10 cada perna',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Extensão isolada de quadril em apoio unipodal e fortalecimento de tríceps sural',
    contraindications: 'Tendinopatia aquileana em fase proliferativa aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'chair-spine-stretch-forward',
    name: 'Spine Stretch Forward na Chair (Alongamento na Chair)',
    apparatus: 'Wunda Chair',
    description: 'Em pé atrás da cadeira, mãos apoiadas sobre o pedal. Enrolar a coluna cervical e torácica para baixo empurrando o pedal com a força abdominal, mantendo a pelve alinhada verticalmente sobre os tornozelos.',
    default_springs: '1 Mola Baixa (pos. 1)',
    default_reps: '5-6',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Alongamento de cadeia posterior contra resistência elástica leve',
    contraindications: 'Lombalgia mecânica aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'chair-teaser',
    name: 'Teaser na Wunda Chair (Teaser na Cadeira)',
    apparatus: 'Wunda Chair',
    description: 'Sentado no solo de costas para a cadeira com mãos no pedal, ou no assento. Elevar pernas em 45º e tronco sustentado no core, controlando o pedal através da força abdominal profunda e estabilização escapular.',
    default_springs: '1 Mola Média (pos. 2)',
    default_reps: '4-5',
    default_sets: 1,
    level: 'avançado',
    postural_focus: 'Controle de transverso do abdômen e depressão escapular em suspensão parcial',
    contraindications: 'Dor facetária lombar, síndrome de impacto do ombro',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'chair-the-cat',
    name: 'The Cat na Wunda Chair (O Gato na Cadeira)',
    apparatus: 'Wunda Chair',
    description: 'Ajoelhado no solo de frente para o pedal, mãos apoiadas sobre ele. Enrolar a coluna em C empurrando o pedal para baixo com o abdômen e retornar desenrolando a coluna com organização das escápulas.',
    default_springs: '1 Mola Alta ou 2 Molas Baixas',
    default_reps: '6-8',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Descompressão espinhal e fortalecimento de serrátil anterior e abdominais',
    contraindications: 'Dor no apoio dos joelhos (usar almofada)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'chair-mermaid',
    name: 'Mermaid na Wunda Chair (Sereia na Cadeira)',
    apparatus: 'Wunda Chair',
    description: 'Sentado de lado sobre o assento com pernas cruzadas ou apoiadas ao lado, uma mão no pedal. Flexionar o tronco lateralmente empurrando o pedal, abrindo o gradil costal do lado oposto e ancorando ambos os ísquios.',
    default_springs: '1 Mola Baixa (pos. 1)',
    default_reps: '5-6 cada lado',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Flexão lateral pura, expansão intercostal e equilíbrio de convexidades escolióticas',
    contraindications: 'Síndrome facetária lombar unilateral em rotação/inclinação',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 5. Ladder Barrel (6 Exercises)
  // ==========================================
  {
    id: 'barrel-ballet-stretches',
    name: 'Ballet Stretches (Alongamentos de Balé no Barril)',
    apparatus: 'Ladder Barrel',
    description: 'Em pé de frente, de lado e de costas para o Ladder Barrel com um membro inferior apoiado sobre a cúpula: alongamento estático e dinâmico de isquiotibiais (Front), adutores e trato iliotibial (Side), e quadríceps/iliopsoas (Back).',
    default_springs: 'N/A (Aparelho sem Molas)',
    default_reps: '30s cada posição',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Flexibilidade de cadeia posterior, adutores e flexores do quadril',
    contraindications: 'Prótese total de quadril com restrição de flexão e adução',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'barrel-short-box',
    name: 'Short Box no Barrel (Série da Caixa Curta no Barril)',
    apparatus: 'Ladder Barrel',
    description: 'Sentado no topo côncavo do barril com pés travados nas travessas da escada: Round Back, Flat Back, Side to Side e Twist, aproveitando a anatomia curva para suporte lombar e amplitude de movimento segura.',
    default_springs: 'N/A (Aparelho sem Molas)',
    default_reps: '5 cada movimento',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Fortalecimento do core apoiado no arco anatômico e mobilidade espinhal',
    contraindications: 'Hérnia lombar aguda que irradia na inclinação posterior',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'barrel-swan',
    name: 'Swan no Ladder Barrel (O Cisne no Barril)',
    apparatus: 'Ladder Barrel',
    description: 'Pelve e coxas apoiadas no ápice do barril, pés firmes nas travessas inferiores da escada. Erguer o tronco a partir de flexão anterior até extensão torácica completa e controlada, sem hiperextensão lombar.',
    default_springs: 'N/A (Aparelho sem Molas)',
    default_reps: '5-6',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Extensão e fortalecimento da musculatura paravertebral torácica e glúteos',
    contraindications: 'Espondilolistese lombar sintomática',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'barrel-side-sit-ups',
    name: 'Side Sit-Ups / Mermaid (Flexão Lateral no Barril)',
    apparatus: 'Ladder Barrel',
    description: 'Quadril e lateral da coxa apoiados no barril, pés travados nas travessas da escada. Mãos atrás da nuca, descer o tronco lateralmente em direção ao chão e subir contra a gravidade ativando oblíquos e quadrado lombar.',
    default_springs: 'N/A (Aparelho sem Molas)',
    default_reps: '6-8 cada lado',
    default_sets: 1,
    level: 'avançado',
    postural_focus: 'Força lateral do tronco, oblíquos e alinhamento contra a gravidade',
    contraindications: 'Instabilidade lumbossacra e lesão costal recente',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'barrel-horseback',
    name: 'Horseback no Barrel (A Cavalo no Barril)',
    apparatus: 'Ladder Barrel',
    description: 'Sentado a cavalo virado para a escada, pernas abraçando o barril com forte adução de coxas. Elevar os braços e o tronco mantendo alongamento axial, fortalecendo assoalho pélvico e adutores de quadril.',
    default_springs: 'N/A (Aparelho sem Molas)',
    default_reps: '5-6',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Ativação adutora profunda e autoalongamento da coluna vertebral',
    contraindications: 'Pubalgia e dor no púbis por estresse adutor',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'barrel-grasshopper',
    name: 'Grasshopper no Barrel (O Gafanhoto no Barril)',
    apparatus: 'Ladder Barrel',
    description: 'Decúbito ventral sobre a cúpula do barril, mãos segurando a travessa superior da escada. Elevar as pernas estendidas e bater os calcanhares (heel beats), fortalecendo glúteos e eretores da espinha com suporte do abdômen.',
    default_springs: 'N/A (Aparelho sem Molas)',
    default_reps: '15-20 batimentos',
    default_sets: 1,
    level: 'intermediário',
    postural_focus: 'Tonificação de glúteo máximo e estabilização lumbopélvica em extensão',
    contraindications: 'Dor anterior no quadril por compressão no barril',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },

  // ==========================================
  // 6. Cinesioterapia & Acessórios (7 Exercises)
  // ==========================================
  {
    id: 'cine-ponte-pelvica-bola',
    name: 'Ponte Pélvica com Bola Suíça (Ponte com Swiss Ball)',
    apparatus: 'Cinesioterapia',
    description: 'Decúbito dorsal com calcanhares e panturrilhas apoiados sobre a Bola Suíça. Elevar a pelve em ponte com co-contração de glúteos, isquiotibiais e core profundo, desafiando a estabilidade e a propriocepção lumbopélvica.',
    default_springs: 'N/A (Bola Suíça 55/65cm)',
    default_reps: '10-12',
    default_sets: 2,
    level: 'iniciante',
    postural_focus: 'Fortalecimento da cadeia posterior e estabilização proprioceptiva lumbopélvica',
    contraindications: 'Cãibras agudas de isquiotibiais (aproximar a bola das coxas)',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cine-abducao-faixa',
    name: 'Abdução de Quadril com Faixa Elástica (Clamshell / Mini-Band)',
    apparatus: 'Cinesioterapia',
    description: 'Decúbito lateral com mini-band acima dos joelhos. Realizar rotação externa e abdução do quadril (Clamshell) mantendo calcanhares unidos, ativando glúteo médio e rotadores profundos do quadril.',
    default_springs: 'Faixa Elástica Média / Forte',
    default_reps: '12-15 cada lado',
    default_sets: 2,
    level: 'iniciante',
    postural_focus: 'Fortalecimento de glúteo médio e prevenção do valgo dinâmico de joelhos',
    contraindications: 'Bursite trocantérica em fase inflamatória aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cine-rotacao-externa-faixa',
    name: 'Rotação Externa de Ombro com Faixa (Manguito Rotador com Theraband)',
    apparatus: 'Cinesioterapia',
    description: 'Em pé ou sentado, cotovelos flexionados a 90º juntos às costelas, segurando a faixa elástica. Rodar os antebraços externamente mantendo escápulas estabilizadas, fortalecendo infraespinhal e redondo menor.',
    default_springs: 'Faixa Elástica Leve / Média',
    default_reps: '12-15',
    default_sets: 2,
    level: 'iniciante',
    postural_focus: 'Estabilização posterior da cabeça umeral e fortalecimento do manguito rotador',
    contraindications: 'Capsulite adesiva em fase de bloqueio articular doloroso',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cine-magic-circle-adutores',
    name: 'Magic Circle Adutores na Ponte (Adução com Anel Flexível)',
    apparatus: 'Cinesioterapia',
    description: 'Decúbito dorsal com joelhos flexionados e pés apoiados no solo, anel flexível entre os côndilos mediais dos joelhos. Pressionar o Magic Circle em adução isométrica sustentada enquanto eleva a pelve em ponte.',
    default_springs: 'Magic Circle / Anel Flexível',
    default_reps: '10 repetições com 3s isometria',
    default_sets: 2,
    level: 'iniciante',
    postural_focus: 'Fortalecimento de adutores de quadril, assoalho pélvico e estabilização lumbopélvica',
    contraindications: 'Osteíte púbica aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cine-extensao-foam-roller',
    name: 'Extensão Torácica no Foam Roller (Mobilização Torácica com Rolo)',
    apparatus: 'Cinesioterapia',
    description: 'Decúbito dorsal com o rolo posicionado horizontalmente na coluna torácica média, mãos na nuca sustentando a cervical. Realizar extensões torácicas suaves expirando na abertura do tórax, aliviando hipercifose postural.',
    default_springs: 'Foam Roller / Rolo de Espuma',
    default_reps: '8-10 mobilizações',
    default_sets: 1,
    level: 'iniciante',
    postural_focus: 'Abertura de caixa torácica, mobilização de vértebras torácicas e alívio da cifose postural',
    contraindications: 'Osteoporose torácica avançada, fratura de costela recente',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cine-scaption-halteres',
    name: 'Elevação Lateral no Plano Escapular (Scaption com Halteres)',
    apparatus: 'Cinesioterapia',
    description: 'Em pé com pelve neutra e escápulas alinhadas, segurando halteres leves. Elevar os membros superiores a 30º à frente do plano coronal até 90º de abdução, fortalecendo deltoide e serrátil sem pinçamento subacromial.',
    default_springs: 'Halteres Leves (1kg a 2kg)',
    default_reps: '10-12',
    default_sets: 2,
    level: 'iniciante',
    postural_focus: 'Fortalecimento do serrátil anterior e controle da discinese escapular',
    contraindications: 'Tendinite bicipital aguda',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cine-wall-squat-bola',
    name: 'Agachamento na Parede com Bola Suíça (Wall Squat com Bola)',
    apparatus: 'Cinesioterapia',
    description: 'Bola Suíça posicionada entre a região lombar do paciente e a parede. Flexionar joelhos até 90º com controle do valgo dinâmico e retorno pelo apoio dos calcanhares, fortalecendo quadríceps e estabilizadores pélvicos.',
    default_springs: 'Bola Suíça 65cm',
    default_reps: '10-12',
    default_sets: 3,
    level: 'iniciante',
    postural_focus: 'Fortalecimento de quadríceps, alinhamento patelofemoral e estabilidade de tronco',
    contraindications: 'Condromalácia patelar grau IV com dor incapacitante a 90º',
    is_custom: 0,
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
];

/**
 * Seeds the classical exercise catalog into the SQLite database.
 * Uses atomic transaction and only seeds if the catalog is currently empty.
 */
export async function seedInitialExercises(db: SQLiteDatabase): Promise<number> {
  const existingCountRow = await db.getFirstAsync<{ count: number }>(
    'SELECT COUNT(*) as count FROM exercises WHERE is_custom = 0;'
  );
  const existingCount = existingCountRow?.count ?? 0;

  if (existingCount >= CLASSICAL_EXERCISES_CATALOG.length) {
    return 0; // Already fully seeded
  }

  let inserted = 0;
  for (const ex of CLASSICAL_EXERCISES_CATALOG) {
    await db.runAsync(
      `INSERT OR IGNORE INTO exercises (
        id, name, apparatus, description, default_springs,
        default_reps, default_sets, level, postural_focus,
        contraindications, is_custom, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);`,
      [
        ex.id,
        ex.name,
        ex.apparatus,
        ex.description ?? null,
        ex.default_springs ?? null,
        ex.default_reps ?? '10',
        ex.default_sets ?? 1,
        ex.level ?? 'iniciante',
        ex.postural_focus ?? null,
        ex.contraindications ?? null,
        0,
        ex.created_at,
        ex.updated_at,
      ]
    );
    inserted++;
  }

  return inserted;
}
